[#177001436] Info from PM
pagopa/backoffice.io.italia.it pull request #44
Opened 2021-02-23 10:37 UTC by vito80ba

This PR implements the call to PM rendering detailed info about payment instrument.

2021-02-23 14:40 UTC, BurnedMarshal requested changes

2021-02-23 14:40 UTC, BurnedMarshal commented on src/components/PaymentMethod.tsx
> +                  popModal(props.walletItemInfo);
We have a typings problem here. `popModal` argument should be `object` and `walletItemInfo` can be undefined. We could be change the signature of this function
```typescript
function popModal(data?: object): void {
    setModalcontent(data === undefined ? "undefined" : JSON.stringify(data, null, 3));
    setModalstate(!modalState);
  }
```

2021-02-23 14:40 UTC, BurnedMarshal commented on src/components/Paymethods.tsx
> +    }
We can simplify with
```suggestion
   setWalletInfo(
      props.wallet?.data.reduce(
        (obj, item) => ({ ...obj, [item.hpan]: item }),
        {} as Record<string, PublicWalletItem>
      )
    );
```

2021-02-23 14:40 UTC, BurnedMarshal commented on src/components/CitizenData.tsx
> +        if (_.status === 200) {
Should we handle the other status code of this API?
- 404 User not found into the PM
- 429 Rate limit exceeded
- 500 Internal server error

2021-02-24 14:48 UTC, BurnedMarshal requested changes

2021-02-24 14:48 UTC, BurnedMarshal commented on src/components/CitizenData.tsx
> +  const [resultErrWallet, setResulterrWalletWallet] = useState<string>("");
This should be
```suggestion
  const [resultErrWallet, setResulterrWallet] = useState<string>("");
```

2021-02-24 15:00 UTC, vito80ba commented on src/components/CitizenData.tsx
> +  const [resultErrWallet, setResulterrWalletWallet] = useState<string>("");
you're right

2021-02-24 15:26 UTC, BurnedMarshal approved these changes
lgtm

2021-03-01 10:26 UTC, BurnedMarshal requested changes

2021-03-01 10:26 UTC, BurnedMarshal commented on src/components/OrphanPaymethods.tsx
> +  const orphans = walletHPANs.filter(x => !paylistHPANs.includes(x));
```suggestion
  const onlyWalletHPANs = walletHPANs.filter(x => !paylistHPANs.includes(x));
```

2021-03-01 10:26 UTC, BurnedMarshal commented on src/i18n.ts
> +      "Payment methods": "Payment methods Cashback enabled",
Could be enabled or not.
```suggestion
      "Payment methods": "Payment methods Cashback",
```

2021-03-01 12:27 UTC, BurnedMarshal approved these changes

2021-03-03 08:50 UTC, merged